theme: jekyll-theme-minimal
markdown: redcarpet
redcarpet:
  extensions:
    [
      'no_intra_emphasis',
      'fenced_code_blocks',
      'autolink',
      'tables',
      'strikethrough',
      'superscript',
      'with_toc_data',
    ]
include:
  - _pages
defaults:
  - scope:
      path: '_pages'
      type: 'pages'
    values:
      permalink: /:basename/
